server:
   port: 9191
   
spring:
  application:
      name: API_GATEWAY
  cloud:
     gateway:
       routes:
         - id:  USER_SERVICE
           uri: lb://USER_SERVICE
           predicates:
              - Path=/users/**
           filters:
            - name: CircuitBreaker
              args:
                name: USER_SERVICE
                fallbackuri: forward:/userServiceFallBack
         - id: DEPARTMENT-SERVICE
           uri: lb://DEPARTMENT-SERVICE
           predicates:
              - Path=/department/**
           filters:
            - name: CircuitBreaker
              args:
                name: DEPARTMENT_SERVICE
                fallbackuri: forward:/departmentServiceFallBack
                
hystrix:
  command:
    fallbackcmd:
      execution:
       isolation:
         thread:
           timeoutInMilliseconds: 4000
       
eureka:
  client:
     register-with-eureka: true
     fetch-registry: true
     service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost